# Generated by Django 2.2 on 2019-12-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna_app', '0003_auto_20191211_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='random', max_length=120)),
                ('description', models.TextField(default="this contains question that can't be categorically specific.")),
            ],
        ),
    ]
